type Bid = {
    id: string,
    type: string,
    key: string,
    from: string,
    status: 'created' | 'cancelled' | 'running' | 'expired' | 'declined' | 'forwarded' | 'authorized',
    reported_at: string,
    archived_at?: string,
    valid_until: string,
    creator: string,
    source: string[],
    sourceComment?: string[],
    options?: Array<'ALLOW_EXTEND_ON_EXPIRED'>,
    target: [],
    targetComment?: string[],
    targetRating: number,
    bidRating?: number,
    logo: string,
    validatorEmails: string,
    currency: 'EUR' | 'DOLLAR',
    puPlace: string[],
    puDate: string,
    puDateRange: string,
    dePlace: string[],
    deDate: string,
    deDateRange: string
    files?: string[],
    vehicle?: string[],
    lang?: string,
    forwarder?: string,
    decision_maker?: string,
    loaded?: 'Yes' | 'No',
    tracker: string,
    driver: string,
    score: Array<number | string>,
    tms: string,
    price: number | string,
    priceDetails?: string[],
};

export default Bid;
